-- MySQL Script generated by MySQL Workbench
-- Thu Jan 18 09:06:21 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mytopicsdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mytopicsdb` ;

-- -----------------------------------------------------
-- Schema mytopicsdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mytopicsdb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `mytopicsdb` ;

-- -----------------------------------------------------
-- Table `mytopicsdb`.`level`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mytopicsdb`.`level` ;

CREATE TABLE IF NOT EXISTS `mytopicsdb`.`level` (
  `levelId` INT NOT NULL,
  `levelName` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`levelId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mytopicsdb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mytopicsdb`.`user` ;

CREATE TABLE IF NOT EXISTS `mytopicsdb`.`user` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(1000) NOT NULL,
  `levelId` INT NOT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `phoneNumber` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`userId`),
  INDEX `user_levelId_idx` (`levelId` ASC) VISIBLE,
  CONSTRAINT `user_levelId`
    FOREIGN KEY (`levelId`)
    REFERENCES `mytopicsdb`.`level` (`levelId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mytopicsdb`.`cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mytopicsdb`.`cart` ;

CREATE TABLE IF NOT EXISTS `mytopicsdb`.`cart` (
  `cartId` INT NOT NULL AUTO_INCREMENT,
  `checkoutTime` DATETIME NULL DEFAULT NULL,
  `isCheckout` TINYINT NULL DEFAULT 0 COMMENT '0:未結帳,1:結帳', 
  `deliveryStatus` ENUM('處理中', '運送中', '已完成', '已取消') NULL DEFAULT NULL,
  `deliveryAddress` VARCHAR(255) NULL DEFAULT NULL,
  `userId` INT NOT NULL,
  `amount` INT NOT NULL,
  PRIMARY KEY (`cartId`),
  INDEX `cart_userId_idx` (`userId` ASC) VISIBLE,
  CONSTRAINT `cart_userId`
    FOREIGN KEY (`userId`)
    REFERENCES `mytopicsdb`.`user` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mytopicsdb`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mytopicsdb`.`category` ;

CREATE TABLE IF NOT EXISTS `mytopicsdb`.`category` (
  `categoryId` INT NOT NULL AUTO_INCREMENT,
  `categoryName` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`categoryId`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mytopicsdb`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mytopicsdb`.`product` ;

CREATE TABLE IF NOT EXISTS `mytopicsdb`.`product` (
  `productId` INT NOT NULL AUTO_INCREMENT,
  `productName` VARCHAR(50) NOT NULL,
  `price` INT NOT NULL,
  `stockQty` INT NOT NULL DEFAULT 0,
  `description` VARCHAR(200) NULL DEFAULT NULL,
  `isLaunch` TINYINT NOT NULL DEFAULT 0 COMMENT '0:未上架,1:上架',
  `categoryId` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`productId`),
  INDEX `product_categoryId_idx` (`categoryId` ASC) VISIBLE,
  CONSTRAINT `product_categoryId`
    FOREIGN KEY (`categoryId`)
    REFERENCES `mytopicsdb`.`category` (`categoryId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mytopicsdb`.`cartItem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mytopicsdb`.`cartItem` ;

CREATE TABLE IF NOT EXISTS `mytopicsdb`.`cartItem` (
  `itemId` INT NOT NULL AUTO_INCREMENT,
  `cartId` INT NOT NULL,
  `productId` INT NOT NULL,
  `price` INT NOT NULL,
  `qty` INT NOT NULL,
  PRIMARY KEY (`itemId`),
  INDEX `cartItem_productId_idx` (`productId` ASC) VISIBLE,
  INDEX `cartItem_cartId_idx` (`cartId` ASC) VISIBLE,
  CONSTRAINT `cartItem_productId`
    FOREIGN KEY (`productId`)
    REFERENCES `mytopicsdb`.`product` (`productId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cartItem_cartId`
    FOREIGN KEY (`cartId`)
    REFERENCES `mytopicsdb`.`cart` (`cartId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mytopicsdb`.`contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mytopicsdb`.`contact` ;

CREATE TABLE IF NOT EXISTS `mytopicsdb`.`contact` (
  `contactId` INT NOT NULL AUTO_INCREMENT,
  `customerName` VARCHAR(255) NOT NULL,
  `customerEmail` VARCHAR(255) NOT NULL,
  `contactTitle` VARCHAR(255) NOT NULL DEFAULT '客戶問題',
  `contactContext` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`contactId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mytopicsdb`.`favorite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mytopicsdb`.`favorite`;

CREATE TABLE IF NOT EXISTS `mytopicsdb`.`favorite` (
  `favoriteId` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NOT NULL,
  `productId` INT NOT NULL,
  PRIMARY KEY (`favoriteId`),
  UNIQUE INDEX `unique_user_product` (`userId`, `productId`) VISIBLE,
  CONSTRAINT `favorite_userId`
    FOREIGN KEY (`userId`)
    REFERENCES `mytopicsdb`.`user` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `favorite_productId`
    FOREIGN KEY (`productId`)
    REFERENCES `mytopicsdb`.`product` (`productId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8mb4
  COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
